In [1]:
import numpy as np

In [111]:
file=open("winequality-red (2).csv")

In [112]:
wines=np.genfromtxt("winequality-red (2).csv",delimiter=";",dtype=float,skip_header=1)

In [67]:
wines=np.loadtxt("winequality-red (2).csv",delimiter=";",dtype=float,skiprows=1)

In [113]:
# print(wines)

In [51]:
print(wines.shape)

(1599, 12)


In [29]:
print(wines[3,4])

0.075


In [30]:
print(wines[:3,4])

[0.076 0.098 0.092]


In [31]:
print(wines[:,2])

[0.   0.   0.04 ... 0.13 0.12 0.47]


In [32]:
print(wines[3,])

[11.2    0.28   0.56   1.9    0.075 17.    60.     0.998  3.16   0.58
  9.8    6.   ]


In [33]:
wines[2,6]

54.0

In [69]:
wines[2,6]=10

In [60]:
wines[2,6]

10.0

In [65]:
slice_new=wines[:,10]
print(slice_new)

[666. 666. 666. ... 666. 666. 666.]


In [62]:
slice_new[:]=666
print(slice_new)

[666. 666. 666. ... 666. 666. 666.]


In [70]:
print(wines)

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]


In [71]:
print(wines.dtype)

float64


In [72]:
wines=wines.astype(int)

In [45]:
print(wines.dtype)

int32


In [46]:
print(wines)

[[ 7  0  0 ...  0  9  5]
 [ 7  0  0 ...  0  9  5]
 [ 7  0  0 ...  0  9  5]
 ...
 [ 6  0  0 ...  0 11  6]
 [ 5  0  0 ...  0 10  5]
 [ 6  0  0 ...  0 11  6]]


In [73]:
wines[:,-1]=wines[:,-1]+10
print(wines)

[[ 7  0  0 ...  0  9 15]
 [ 7  0  0 ...  0  9 15]
 [ 7  0  0 ...  0  9 15]
 ...
 [ 6  0  0 ...  0 11 16]
 [ 5  0  0 ...  0 10 15]
 [ 6  0  0 ...  0 11 16]]


In [74]:
print(np.sum(wines))

161485


In [75]:
print(np.sum(wines[:,0]))

12589


In [76]:
print(np.sum(wines,axis=1))

[ 80 128  61 ... 107 111  99]


In [77]:
print(np.sum(wines,axis=0))

[12589    24     1  3350     0 25382 74257    81  4770    60 15969 25002]


In [78]:
wines[:,-1]=wines[:,-1]+wines[:,-1]
print(wines)

[[ 7  0  0 ...  0  9 30]
 [ 7  0  0 ...  0  9 30]
 [ 7  0  0 ...  0  9 30]
 ...
 [ 6  0  0 ...  0 11 32]
 [ 5  0  0 ...  0 10 30]
 [ 6  0  0 ...  0 11 32]]


In [79]:
wines[:,-2]=wines[:,-2]*wines[:,-1]
print(wines)

[[  7   0   0 ...   0 270  30]
 [  7   0   0 ...   0 270  30]
 [  7   0   0 ...   0 270  30]
 ...
 [  6   0   0 ...   0 352  32]
 [  5   0   0 ...   0 300  30]
 [  6   0   0 ...   0 352  32]]


In [81]:
print(wines[:,-1]>5)

[ True  True  True ...  True  True  True]


In [83]:
print(wines[:,-1]==10)

[False False False ... False False False]


In [84]:
print(wines[:,-1]>7)

[ True  True  True ...  True  True  True]


In [97]:
a=wines[:,-1]>7
b=wines[:,-3]>10
print(b[a])

[False False False ... False False False]


In [98]:
print(wines.shape)

(1599, 12)


In [102]:
wines=wines.reshape(12,1599)

In [103]:
print(wines.shape)


(12, 1599)


In [104]:
print(wines)

[[  7   0   0 ...   6   0   0]
 [  1   0  17 ...   3   0  26]
 [ 61   1   3 ...  42   0   3]
 ...
 [  2   0  23 ...   1   0   6]
 [ 25   0   3 ...  53   0   3]
 [  0 270  30 ...   0 352  32]]
